# An image to test the UC2-REST 
# sudo docker build -t uc2_rest .
# docker run -it --rm --privileged uc2_rest
FROM ubuntu:22.04

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    python3 \
    python3-pip \
    sudo \
    usbutils \
    git 

# Create the udev rules directory
RUN mkdir -p /etc/udev/rules.d

# Install UC2-REST
RUN git clone https://github.com/openUC2/UC2-REST /tmp/UC2-REST && \
    cd /tmp/UC2-REST && \
    pip install -e /tmp/UC2-REST && \
    pip install jupyterlab jupyter
    

# run python file 
CMD python3 /tmp/UC2-REST/uc2rest/TEST/TEST_ESP32_Serial.py


#CMD echo 'LSUSB' && lsusb && \
#    cd /tmp/UC2-REST/uc2rest/ && \
#    jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root

# CMD /bin/bash
