version: '3'
services:
  imswitch:
    image: ghcr.io/openuc2/imswitch-noqt-amd64:latest
    container_name: imswitch
    ports:
      - 8001:8001
      - 8003:8002
      - 2222:22
      - 8889:8888
    environment:
      HEADLESS: 1
      HTTP_PORT: 8001
      CONFIG_FILE: example_virtual_microscope.json
      UPDATE_GIT: 0
      UPDATE_CONFIG: 0
      CONFIG_PATH: /config
      ssl: 0
    volumes:
      - "~/:/config"
    privileged: true
    restart: always
