FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE=true

# Install system dependencies
RUN apt-get update && apt-get install -y \
        udev \
        libusb-1.0-0 \
        ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install VmbPy from PyPI (VimbaX Python API)
RUN python -m pip install --no-cache-dir vmbpy

# Copy our test script
COPY list_cameras.py /opt/

# Set working directory
WORKDIR /opt

# Set entrypoint to our test script by default
ENTRYPOINT ["python", "list_cameras.py"]